# Generated by Django 6.0.4 on 2026-05-07 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('emails', models.JSONField(default=list)),
                ('emails_copia', models.JSONField(blank=True, default=list)),
                ('tipo', models.CharField(default='proveedor', max_length=50)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='catalogo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_componente', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('namespace', models.CharField(max_length=200)),
                ('app_label', models.CharField(max_length=200)),
                ('terminos_log', models.JSONField(blank=True, default=list)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='catalogo.servicio')),
            ],
        ),
    ]
