# Generated by Django 6.0.4 on 2026-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_id', models.CharField(max_length=100)),
                ('servicio_nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('hora_inicio_novedad', models.DateTimeField()),
                ('componentes_afectados', models.JSONField(default=list)),
                ('destinatarios', models.JSONField(default=list)),
                ('asunto_correo', models.CharField(blank=True, max_length=300)),
                ('cuerpo_correo', models.TextField(blank=True)),
                ('logs_recopilados', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
