# Generated by Django 6.0.4 on 2026-05-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeNotificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_id', models.CharField(max_length=200, unique=True)),
                ('remitente', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('escalamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.escalamiento')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
