# Generated by Django 6.0.4 on 2026-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_mensajenotificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajenotificado',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
