# Generated by Django 6.0.4 on 2026-05-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_mensajenotificado_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajenotificado',
            name='escalamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incidencias.escalamiento'),
        ),
    ]
