# Generated by Django 6.0.4 on 2026-05-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_alter_mensajenotificado_escalamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamiento',
            name='destinatarios_copia',
            field=models.JSONField(default=list),
        ),
    ]
